use_frameworks!

platform :ios, '8.0'

target 'HcdemoLib_Example' do
  pod 'HcdemoLib', :path => '../'

  target 'HcdemoLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
